# Generated by Django 3.2.5 on 2021-11-24 08:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0003_auto_20211124_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=264, unique=True),
        ),
    ]
