# Generated by Django 3.2.5 on 2021-11-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0004_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='Telephone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_add',
        ),
    ]
