# Generated by Django 3.2.5 on 2021-12-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.IntegerField(default='10000'),
        ),
    ]
