# Generated by Django 3.2.5 on 2021-12-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0007_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.CharField(default='$10000', max_length=264),
        ),
    ]
