# Generated by Django 3.2.5 on 2021-12-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0008_alter_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=11),
        ),
    ]
