# Generated by Django 3.2.5 on 2021-12-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0009_alter_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=models.IntegerField(default=5000),
        ),
    ]
