# Generated by Django 3.2.5 on 2021-12-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0011_auto_20211208_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.CharField(default='', max_length=264),
        ),
    ]
