# Generated by Django 3.2.5 on 2021-12-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0012_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='option',
            field=models.CharField(default='', max_length=264),
        ),
    ]
