# Generated by Django 3.2.5 on 2021-12-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0014_alter_user_email_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='homepage',
            field=models.IntegerField(default='1', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='innerpages',
            field=models.IntegerField(default='1', max_length=128),
        ),
    ]
