# Generated by Django 3.2.5 on 2021-12-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0023_auto_20211209_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='innerpages',
            new_name='innerpage',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='homepage',
            new_name='webpagehome',
        ),
    ]
