# Generated by Django 3.2.5 on 2021-12-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0025_rename_innerpage_user_innerpages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='innerpages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='webpagehome',
        ),
    ]
