# Generated by Django 3.2.5 on 2021-12-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0026_auto_20211209_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='homepage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='innerpages',
            field=models.IntegerField(default=1),
        ),
    ]
