# Generated by Django 3.2.5 on 2021-12-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0028_alter_user_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='innerpages',
            field=models.IntegerField(default=1),
        ),
    ]
