# Generated by Django 3.2.5 on 2021-12-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0035_auto_20211210_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='user',
            name='budget_currency',
        ),
    ]
