# Generated by Django 3.2.5 on 2021-12-16 04:21

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0037_auto_20211216_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=264, region=None),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=264),
        ),
    ]
