# Generated by Django 3.2.5 on 2021-12-16 04:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0038_auto_20211216_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=264, region=None),
        ),
    ]
