# Generated by Django 3.2.5 on 2021-12-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0041_alter_user_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Telephone',
            new_name='telephone',
        ),
    ]
