# Generated by Django 3.2.5 on 2021-12-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0042_rename_telephone_user_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
    ]
