# Generated by Django 3.2.5 on 2021-12-16 05:59

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0045_auto_20211216_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
    ]
