# Generated by Django 3.2.5 on 2021-12-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0049_auto_20211217_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.CharField(default='', max_length=264),
        ),
    ]
