# Generated by Django 3.2.5 on 2021-12-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0050_user_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notes',
            new_name='html_development_notes',
        ),
    ]
