# Generated by Django 4.0 on 2021-12-29 05:47

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0052_auto_20211218_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
    ]
