# Generated by Django 4.0 on 2022-01-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0060_alter_user_seo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seo_options',
            field=models.CharField(default='', max_length=264),
        ),
    ]
