# Generated by Django 4.0 on 2022-01-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0061_alter_user_seo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digital_options',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='seo_options',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
