# Generated by Django 4.0 on 2022-01-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0062_user_digital_options_alter_user_seo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecom_development_notes',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='user',
            name='ecom_options',
            field=models.CharField(default='', max_length=264),
        ),
    ]
