# Generated by Django 4.0 on 2022-01-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0065_alter_user_digital_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='digital_options',
            field=models.TextField(),
        ),
    ]
