# Generated by Django 4.0 on 2022-01-20 06:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0067_alter_user_seo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email_add', models.EmailField(max_length=264)),
                ('Mobile', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('Experience', models.CharField(max_length=128)),
                ('Apply_for', models.CharField(max_length=128)),
                ('file_upload', models.FileField(upload_to='')),
            ],
        ),
    ]
