# Generated by Django 4.0 on 2022-01-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0069_alter_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
