# Generated by Django 4.0 on 2022-01-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0075_alter_job_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='file_upload',
        ),
    ]
